name: generator

on:
  workflow_dispatch:
  schedule:
  - cron: "09 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.15.2
    - run: npm ci
    - name: Generate quote
      run: npm run generate
    - name: Update README.md
      run: |
        git config --global user.email "hoahoangnanh20012001@gmail.com"
        git config --global user.name "hoanganhnh"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push